# Linguagem

prog        ::= funcs

funcs       ::= func funcs
              | NULL
func        ::= type id(params) { stmts }

params      ::= param tail
              | NULL
tail        ::= , param tail
              | NULL
param       ::= type id

stmts       ::= stmt stmts
              | NULL

stmt        ::= decl;
	          | assign;
              | call;
              | return bool;
              | blok

decl        ::= type id index value
index       ::= [ integer ]
              | NULL
value       ::= = bool
	          | NULL

assign      ::= plusplus local
              | local plusplus
              | local oper = bool

block       ::= { stmts }
              | if (bool) stmts
              | if (bool) stmts else stmts
              | while (bool) stmts
              | do stmts while (bool);
              | for (decl ; bool ; assign) stmts
              | for (assign ; bool ; assign) stmts

plusplus    ::= ++
              | --

oper        ::= +
              | -
              | *
              | /
              | %
              | &
              | |
              | NULL

local       ::= id position
position    ::= [bool]
              | NULL

bool        ::= join lor
lor         ::= || join lor
              | NULL

join        ::= equality land
land        ::= && equality land
              | NULL

equality    ::= rel eqdif
eqdif       ::= == rel eqdif
              | != rel eqdif
              | NULL

rel         ::= ari comp
comp        ::= < ari comp
              | <= ari comp
              | > ari comp
              | >= ari comp
              | NULL

ari         ::= term oper
oper        ::= + term oper
              | - term oper
              | NULL

term        ::= unary calc
calc        ::= * unary calc
              | / unary calc
              | % unary calc
              | NULL

unary       ::= !unary
              | -unary
              | factor

factor      ::= (bool)
              | call
              | local
              | integer
              | real
              | true
              | false

call        ::= id(args)
args        ::= bool tailAr
              | NULL
tailAr      ::= , bool tailAr
              | NULL
